In [23]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os
from scipy.stats import sem

# Hide warning messages in notebook
import warnings
warnings.filterwarnings("ignore")

# File to Load (Remember to Change These)
dataset_2016 = "Dataset/2016.csv"
dataset_2017 = "Dataset/2017.csv"
dataset_2018 = "Dataset/2018.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
dataset_2016_df = pd.read_csv(dataset_2016)
dataset_2017_df = pd.read_csv(dataset_2017)
dataset_2018_df = pd.read_csv(dataset_2018)

# Combine the data into a single dataset
merge_2016_2017_df = pd.merge(dataset_2016_df, dataset_2017_df , on="Country")

merge_2016_2017_df = merge_2016_2017_df.rename(columns={"Happiness Rank_x":"2016 Happiness Rank", "Happiness Score_x":"2016 Happiness Score", "Economy (GDP per Capita)_x":"2016 Economy (GDP per Capita)", "Health (Life Expectancy)_x":"2016 Health (Life Expectancy)", "Freedom_x":"2016 Freedom"})
merge_2016_2017_df = merge_2016_2017_df.rename(columns={"Happiness Rank_y":"2017 Happiness Rank", "Happiness Score_y":"2017 Happiness Score", "Economy (GDP per Capita)_y":"2017 Economy (GDP per Capita)", "Health (Life Expectancy)_y":"2017 Health (Life Expectancy)", "Freedom_y":"2017 Freedom"})



merge_dataset_df = pd.merge(merge_2016_2017_df, dataset_2018_df , on="Country")
merge_dataset_df = merge_dataset_df.rename(columns={"Happiness Rank":"2018 Happiness Rank", "Happiness Score":"2018 Happiness Score", "Economy (GDP per Capita)":"2018 Economy (GDP per Capita)", "Health (Life Expectancy)":"2018 Health (Life Expectancy)", "Freedom":"2018 Freedom"})


# Display the data table for preview
# combined_data_df["Mouse ID"].value_counts()

merge_dataset_df.head()
# list(merge_dataset_df.columns)

,Country,2016 Happiness Rank,2016 Happiness Score,2016 Economy (GDP per Capita),2016 Health (Life Expectancy),2016 Freedom,2017 Happiness Rank,2017 Happiness Score,2017 Economy (GDP per Capita),2017 Health (Life Expectancy),2017 Freedom,2018 Happiness Rank,2018 Happiness Score,2018 Economy (GDP per Capita),2018 Health (Life Expectancy),2018 Freedom
0,Denmark,1,7.526,1.44178,0.79504,0.57941,2,7.522,1.482383,0.792566,0.626007,3,7.555,1.351,0.868,0.683
1,Switzerland,2,7.509,1.52733,0.86303,0.58557,4,7.494,1.564980,0.858131,0.620071,5,7.487,1.420,0.927,0.660
2,Iceland,3,7.501,1.42666,0.86733,0.56624,3,7.504,1.480633,0.833552,0.627163,4,7.495,1.343,0.914,0.677
3,Norway,4,7.498,1.57744,0.79579,0.59609,1,7.537,1.616463,0.796667,0.635423,2,7.594,1.456,0.861,0.686
4,Finland,5,7.413,1.40598,0.81091,0.57104,5,7.469,1.443572,0.809158,0.617951,1,7.632,1.305,0.874,0.681